### ISSUE TITLE
Form broken as it cannot find id for errorText HMTL

### ISSUE THREAD

**Issue by mineshmshah** [FACed-Off/week1-project-mango#20]
### Expected outcome 

Form should not send when the name has a digit in it

### Actual Outcome 

The form fails as there is a bug in the code. The `js` fails here because it cannot find the id with `errorText`. This means it can't find innerHTML and the function fails. As a result the form sends. This tag needs to be added to HTML somewhere.

Note: Numbers can be allowed in names - look at Elon Musk's new kid

**Comment by MeeranB** [comment]
Fixed within commit 890a551265a441dc352248acbcfd0ae326375e0a
In regards to the validity of the restriction, perhaps we should add a feature that asks for confirmation of form submission when adding a numerical character into the name field, as opposed to removing the ability to submit the name entirely.
