### ISSUE TITLE
Clean up javascript function

### ISSUE THREAD

**Issue by mineshmshah** [FACed-Off/week1-project-mango#21]
A few points to improve:

- The JS function can be simplified into one single function that returns true or false. It is abstracted for no real reason here. 
- nameValidation() runs twice
- you could simply `return nameValidation()` instead of
```
  if (nameValidation()) {
    //Passes validation if name validation is successful
    console.log('here')
    return true;
  } else {
    //Fails validation if name validation is unsuccessful
    return false;
  }
```

Again can be done in one function returning true or false

Positives
- It is awesome you all tried this and tried using regex!

**Comment by MeeranB** [comment]
Removed validateForm function entirely, scalability not needed in this instance
